# Generated by Django 5.0.14 on 2026-08-13 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_scavcomm_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_year', models.PositiveIntegerField(blank=True, help_text='Graduation year representing the submitting class, if assigned.', null=True)),
                ('submitted_answer', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('awarded_points', models.IntegerField(blank=True, help_text='Points awarded, if this submission was correct.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.challenge')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_submissions', to='core.participant')),
                ('solve', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission', to='core.challengesolve')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
