# Generated by Django 5.0.14 on 2026-08-13 19:23

from django.db import migrations


def backfill_submissions(apps, schema_editor):
    ChallengeSolve = apps.get_model("core", "ChallengeSolve")
    ChallengeSubmission = apps.get_model("core", "ChallengeSubmission")

    solves = list(ChallengeSolve.objects.filter(submission__isnull=True))
    created = ChallengeSubmission.objects.bulk_create(
        [
            ChallengeSubmission(
                challenge_id=solve.challenge_id,
                participant_id=solve.participant_id,
                team_year=solve.team_year,
                submitted_answer=solve.submitted_answer,
                is_correct=True,
                awarded_points=solve.awarded_points,
                solve_id=solve.id,
            )
            for solve in solves
        ]
    )

    # bulk_create still applies auto_now_add, stamping "now" instead of the
    # solve's original time, so fix up created_at with a plain .update()
    # (which does not trigger auto_now_add).
    for submission, solve in zip(created, solves):
        ChallengeSubmission.objects.filter(pk=submission.pk).update(
            created_at=solve.created_at
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_challengesubmission'),
    ]

    operations = [
        migrations.RunPython(backfill_submissions, noop_reverse),
    ]
