# Generated by Django 5.0.14 on 2026-08-14 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_backfill_challenge_submissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.SlugField(help_text="The path segment used after /s/, e.g. 'clue1' for /s/clue1/.", max_length=64, unique=True)),
                ('target_url', models.URLField(help_text='The destination the short link redirects to.', max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='short_links', to='core.participant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
