# Generated by Django 5.0.14 on 2026-08-14 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_shortlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='allow_multiple_solves',
        ),
    ]
